[build]
  command = "node ./tools/CI/create-env.js && npx cypress install && gatsby build"
  publish = "public/"

[build.environment]
  DEBUG = "netlify-plugin-cypress"
  # cache Cypress binary in local "node_modules" folder
  # so Netlify caches it
  CYPRESS_CACHE_FOLDER = "./node_modules/.cache/netlify-cypress/"
  # set TERM variable for terminal output
  TERM = "xterm"

[template]
  incoming-hooks = ["Ghost"]

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[plugins]]
  # local Cypress plugin will test our site after it is built
  package = "netlify-plugin-cypress"
  [plugins.inputs]
    record = true
    group = "built site"
