[build]
  command = "node ./tools/CI/create-env.js && gatsby build && chmod a+x ./tools/CI/trigger-circle.sh && ./tools/CI/trigger-circle.sh"
  publish = "public/"

[template]
  incoming-hooks = ["Ghost"]
