# Check https://circleci.com/docs/2.0/ for more details
# for config.yml syntax see https://circleci.com/docs/2.0/configuration-reference/
version: 2
jobs:
  build:
    docker:
      # find Docker image at https://github.com/cypress-io/cypress-docker-images
      - image: cypress/base:12.14.0
        environment:
          ## this enables colors in the output
          TERM: xterm

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies for the app and for tests
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}-{{ checksum "package.json" }}
            - dependencies-{{ .Branch }}
            - dependencies

      # Installs NPM dependencies quickly
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          key: dependencies-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            # all NPM modules
            - ~/.npm
            - node_modules
            # Cypress binary (or yarn dependencies)
            - ~/.cache  ## cache both yarn and Cypress!

      - run:
          name: Run server and E2E tests locally or against external URL
          command: |
            echo CYPRESS_RECORD_KEY=$CYPRESS_RECORD_KEY >> .env
            echo GHOST_API_URL=$GHOST_API_URL >> .env
            echo GHOST_CONTENT_API_KEY=$GHOST_CONTENT_API_KEY >> .env
            if [[ -v CYPRESS_baseUrl ]]; then
              echo Testing external url $CYPRESS_baseUrl
              yarn ci:cy:run
            else
              echo Running local server and testing it
              yarn ci:test
            fi

      - store_test_results:
          path: ~/repo/cypress/results

      - store_artifacts:
          path: ~/repo/cypress/screenshots
      - store_artifacts:
          path: ~/repo/cypress/videos

workflows:
  version: 2
  tests:
    jobs:
      - build
