# Check https://circleci.com/docs/2.0/ for more details
# for config.yml syntax see https://circleci.com/docs/2.0/configuration-reference/
version: 2
jobs:
  build:
    docker:
      # find Docker image at https://github.com/cypress-io/cypress-docker-images
      - image: cypress/base:12.14.0
        environment:
          ## this enables colors in the output
          TERM: xterm

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies for the app and for tests
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      # Installs NPM dependencies quickly
      - run:
          name: Install dependencies
          command: |-
            npm install -g gatsby-cli
            yarn install --frozen-lockfile

      - run:
          name: Check security vulnerabilities
          command: yarn snyk-protect

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache  ## cache both yarn and Cypress!

      - run:
          name: Run server and E2E tests locally or against external URL
          command: |-
            echo "CYPRESS_RECORD_KEY=$CYPRESS_RECORD_KEY" >> .env
            echo "GHOST_API_URL=$GHOST_API_URL" >> .env
            echo "GHOST_CONTENT_API_KEY=$GHOST_CONTENT_API_KEY" >> .env
            echo "CONTACT_FORM_ENDPOINT=$CONTACT_FORM_ENDPOINT" >> .env
            echo "RECAPTCHA_SITE_KEY=$RECAPTCHA_SITE_KEY" >> .env
            if [[ -v CYPRESS_baseUrl ]]; then
              echo "Testing external url $CYPRESS_baseUrl"
              gatsby build
              yarn ci:cy:run || yarn ci:cy:run:no-record
            else
              echo "Running local server and testing it"
              yarn ci:test || yarn ci:test:no-record
            fi

      - store_test_results:
          path: ~/repo/cypress/results

      - store_artifacts:
          path: ~/repo/cypress/screenshots
      - store_artifacts:
          path: ~/repo/cypress/videos

workflows:
  version: 2
  tests:
    jobs:
      - build
