# Check https://circleci.com/docs/2.0/ for more details
# for config.yml syntax see https://circleci.com/docs/2.0/configuration-reference/
version: 2
jobs:
  build:
    docker:
      # find Docker image at https://github.com/cypress-io/cypress-docker-images
      - image: cypress/base:13.6.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies for the app and for tests
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-

      # Installs NPM dependencies quickly
      - run:
          name: Install dependencies
          command: yarn

      - save_cache:
          paths:
            # all NPM modules
            - ~/.npm
            # Cypress binary (or yarn dependencies)
            - ~/.cache
          key: dependencies-{{ checksum "package.json" }}

      - run:
          name: Run server and E2E tests locally or against external URL
          command: |
            if [[ -v CYPRESS_baseUrl ]]; then
              echo Testing external url $CYPRESS_baseUrl
              yarn cy:run
            else
              echo Running local server and testing it
              yarn test
            fi

      - store_artifacts:
          path: ~/repo/cypress/screenshots
      - store_artifacts:
          path: ~/repo/cypress/videos

workflows:
  version: 2
  tests:
    jobs:
      - build
